services:
  wiremock:
    image: wiremock/wiremock:3.3.1-1
    ports:
      - 8080:8080
    healthcheck:
      test: curl http://wiremock:8080/__admin/health
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    command:
      --local-response-templating
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
